### PR TITLE
Reactive Architecture

### PR DESCRIPTION
**Pull request by wokalski**
Ok, my commit messages are funny but I should stop this.

Kidding aside, this is a bit retarded.

Why? 
It lacks some separation of concerns. Basically model logic is inside `GridComponent` which is a bit anti pattern. Keep working. I made it compile and work.

### CODE REVIEW

**Comment by wokalski** [comment]
Oh, and it crashes at the end.
Oh, and you can cheat if you quickly select buttons

**Comment by maartenschumacher** [comment]
It's kind of not what I wanted. I guess there should have been a ticket :)

The goal was to have this `outputStream` that replaces the `apply(state)` function calls. The thing is that sometimes when components pass desired state to their parents, they need to check for current state. For example, when a button gets tapped we have to make sure it's `.Empty` before we pass it onwards. This is now done with a state variable, but I thought if we have this `outputStream` instead the component can just check the most recent value of its `outputStream`. So no more variables, and we define those dependencies declaratively. 

But the problem is this circular dependency that it creates. This is what cycle.js would solve, and I'm gonna see if I can implement something similar for this project.

**Comment by wokalski** [comment]
My PR aside. My biggest concern is **where** you want to put the observing logic aka `subscribeNext` imp.

**Comment by maartenschumacher** [comment]
It should be right at the end then. Only when actually updating the UI. So instead of calling `self.apply(state)`, `subscribeNext` would directly call `self.button.setTitle(...` in the button component. Then in the rest of the app you should never use `subscribeNext`.

**Comment by wokalski** [comment]
but **where** in the component. Where should it be defined.

**Comment by maartenschumacher** [comment]
Ah. Well in the init it would be.

**Pull request closed without merging**
